# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - docs
      - asset
      - .vscode
      - README.md

  pull_request:
    branches:
      - master
    paths-ignore:
      - docs
      - asset
      - .vscode
      - README.md

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: c-hive/gha-yarn-cache@v1
    - name: 下载依赖
      run: yarn
    - name: pre-release
      run: yarn build #没有nrm改用build
    - name: 单元测试
      run: yarn test
